In [17]:
import numpy as np

size=input("Enter the grid size")
gridsize=int(size)
map_grid = np.random.randint(0, 2, (gridsize, gridsize))
map_grid = np.flipud(map_grid) 
for row in reversed(map_grid):   
    print(row)

n = len(map_grid)  
m = 3              

max_damage = 0             
best_center = (0,0)        
destroyed_islands = []     


for y in range(n):         
    for x in range(n):     
        
        
        if x - m//2 < 0 or x + m//2 >= n:
            continue        
        if y - m//2 < 0 or y + m//2 >= n:
            continue        
        
        if map_grid[y][x] == 1:
            
            damage = 0             
            temp_islands = []      
            
            
            for i in range(y - m//2, y + m//2 + 1):
                for j in range(x - m//2, x + m//2 + 1):
                    if map_grid[i][j] == 1:
                        damage += 1
                        temp_islands.append((j, i))  
            
        
            if damage > max_damage:
                max_damage = damage
                best_center = (x, y)
                destroyed_islands = temp_islands


print("Best bomb center:", best_center)
print("Maximum islands destroyed:", max_damage)
print("Coordinates of destroyed islands:", destroyed_islands)


Enter the grid size 4


[1 0 0 1]
[0 0 0 1]
[0 1 1 0]
[0 0 0 0]
Best bomb center: (2, 1)
Maximum islands destroyed: 3
Coordinates of destroyed islands: [(1, 1), (2, 1), (3, 2)]
